### ISSUE TITLE
Update to apiv3-docs or new repo?

### ISSUE THREAD

**Issue by subinsebastien** [teamsnap/apiv2-docs#1]
I would like to analyse the newer version of the API and would like to develop third-party apps on top of Teamsnap. Per the website, the API is now on v3 and no detailed docs available for the specific version.

**Comment by locriani** [comment]
Our APIv3 documentation is available here: http://developer.teamsnap.com/documentation/apiv3/getting_started/

That will be the home of the APIv3 documentation. We have no plans (at this time) of setting up APIv3 documentation in a similar way to the documentation presented here.

Thanks!
